//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireLoadCalculator.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FireLoadCalculator.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Combustion heat [MJ/kg].
        /// </summary>
        internal static string AllMaterialsCombustionHeat {
            get {
                return ResourceManager.GetString("AllMaterialsCombustionHeat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string AllMaterialsName {
            get {
                return ResourceManager.GetString("AllMaterialsName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reduction factor [%].
        /// </summary>
        internal static string AllMaterialsReductionFactor {
            get {
                return ResourceManager.GetString("AllMaterialsReductionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Area [m²].
        /// </summary>
        internal static string AllRoomsArea {
            get {
                return ResourceManager.GetString("AllRoomsArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add room.
        /// </summary>
        internal static string AllRoomsControlsAdd {
            get {
                return ResourceManager.GetString("AllRoomsControlsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Confirm changes.
        /// </summary>
        internal static string AllRoomsControlsModify {
            get {
                return ResourceManager.GetString("AllRoomsControlsModify", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stored materials.
        /// </summary>
        internal static string AllRoomsMaterials {
            get {
                return ResourceManager.GetString("AllRoomsMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        internal static string AllRoomsName {
            get {
                return ResourceManager.GetString("AllRoomsName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter room area....
        /// </summary>
        internal static string AllRoomsPopupEnterArea {
            get {
                return ResourceManager.GetString("AllRoomsPopupEnterArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter room name....
        /// </summary>
        internal static string AllRoomsPopupEnterName {
            get {
                return ResourceManager.GetString("AllRoomsPopupEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Count.
        /// </summary>
        internal static string AllRoomsPopupMaterialsCounts {
            get {
                return ResourceManager.GetString("AllRoomsPopupMaterialsCounts", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Material name.
        /// </summary>
        internal static string AllRoomsPopupMaterialsNames {
            get {
                return ResourceManager.GetString("AllRoomsPopupMaterialsNames", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Weight [kg].
        /// </summary>
        internal static string AllRoomsPopupMaterialsWeights {
            get {
                return ResourceManager.GetString("AllRoomsPopupMaterialsWeights", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total zone area [m²].
        /// </summary>
        internal static string AllRoomsSummaryArea {
            get {
                return ResourceManager.GetString("AllRoomsSummaryArea", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total zone fire load density [MJ/m²].
        /// </summary>
        internal static string AllRoomsSummaryFireLoad {
            get {
                return ResourceManager.GetString("AllRoomsSummaryFireLoad", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fire load density [MJ/m²].
        /// </summary>
        internal static string AllRoomsTotalFireLoad {
            get {
                return ResourceManager.GetString("AllRoomsTotalFireLoad", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        internal static string CommonAdd {
            get {
                return ResourceManager.GetString("CommonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        internal static string CommonDelete {
            get {
                return ResourceManager.GetString("CommonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        internal static string CommonEdit {
            get {
                return ResourceManager.GetString("CommonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No items to display.
        /// </summary>
        internal static string CommonMessageNoItems {
            get {
                return ResourceManager.GetString("CommonMessageNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New.
        /// </summary>
        internal static string CommonNew {
            get {
                return ResourceManager.GetString("CommonNew", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        internal static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fire load density.
        /// </summary>
        internal static string MenuItem1 {
            get {
                return ResourceManager.GetString("MenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Water tank capacity for external fire extinguishing.
        /// </summary>
        internal static string MenuItem2 {
            get {
                return ResourceManager.GetString("MenuItem2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Materials.
        /// </summary>
        internal static string MenuItem3 {
            get {
                return ResourceManager.GetString("MenuItem3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter the fire load density [MJ/m²].
        /// </summary>
        internal static string WaterReservoirField1 {
            get {
                return ResourceManager.GetString("WaterReservoirField1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter the amount of water available from the hydrant network [dm³/s].
        /// </summary>
        internal static string WaterReservoirField2 {
            get {
                return ResourceManager.GetString("WaterReservoirField2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter the area of the fire zone [m²].
        /// </summary>
        internal static string WaterReservoirField3 {
            get {
                return ResourceManager.GetString("WaterReservoirField3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amount of water required for external fire extinguishing [dm³/s].
        /// </summary>
        internal static string WaterReservoirField4 {
            get {
                return ResourceManager.GetString("WaterReservoirField4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wrongly parsed/Missing data!.
        /// </summary>
        internal static string WaterReservoirField4Error {
            get {
                return ResourceManager.GetString("WaterReservoirField4Error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Missing amount of water for external fire extinguishing [dm³/s].
        /// </summary>
        internal static string WaterReservoirField5 {
            get {
                return ResourceManager.GetString("WaterReservoirField5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No need to build a fire water tank.
        /// </summary>
        internal static string WaterReservoirField5NoNeed {
            get {
                return ResourceManager.GetString("WaterReservoirField5NoNeed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Relative duration of the fire [h].
        /// </summary>
        internal static string WaterReservoirField6 {
            get {
                return ResourceManager.GetString("WaterReservoirField6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Required capacity of the fire water tank [m³].
        /// </summary>
        internal static string WaterReservoirField7 {
            get {
                return ResourceManager.GetString("WaterReservoirField7", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fire duration too long!.
        /// </summary>
        internal static string WaterReservoirField7VeryHigh {
            get {
                return ResourceManager.GetString("WaterReservoirField7VeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use internal data.
        /// </summary>
        internal static string WaterReservoirUseInternal {
            get {
                return ResourceManager.GetString("WaterReservoirUseInternal", resourceCulture);
            }
        }
    }
}
